name: Build
on:
  push:
    branches: main
permissions:
  contents: read
  pages: write
  id-token: write
env:
  NODE_VERSION: "22.11"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build static files
        run: npm run build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
